"""Secrets and the configuration file read by systemd."""

import re
import secrets
import string
from pathlib import Path

from lib.constants import (DEFAULT_PORT, ENV_FILE, SECRET_LENGTH,
                           SECRET_MIN_LENGTH, DB_USER)
from lib.step_base import Step


def _generate_secret(length: int = SECRET_LENGTH) -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _escape(value) -> str:
    """Make a value safe inside quotes in an EnvironmentFile.

    systemd applies C-style escapes to quoted values: without this,
    a backslash would be reinterpreted (``\\t`` becomes a
    tab) and a quote would close the string. Newlines are removed entirely
    because they would allow arbitrary lines to be added to the file.
    """
    text = str(value or "")
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    return text.replace("\n", " ").replace("\r", " ")


def _read_existing(path: Path) -> dict:
    values = {}
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            match = re.match(r'^([A-Z0-9_]+)=("?)(.*?)\2$', line.strip())
            if match:
                values[match.group(1)] = match.group(3)
    except OSError:
        pass
    return values


class EnvConfigStep(Step):
    def __init__(self):
        super().__init__("Configurazione", "Chiavi segrete e parametri del servizio")

    def execute(self, runner, sysinfo, config: dict) -> bool:
        self.start()

        existing = _read_existing(ENV_FILE)

        # Regenerating the session key on every run would log out all connected
        # users. An update must not disconnect anyone, so reuse the existing key.
        session_key = existing.get("AUTH_SESSION_KEY") or _generate_secret()
        backup_token = existing.get("BACKUP_ADMIN_TOKEN") or _generate_secret()
        if existing.get("AUTH_SESSION_KEY"):
            runner.log("    chiave di sessione esistente riusata: nessuno viene disconnesso")

        # With fewer than 16 characters, Quarkus returns 500 for every request
        # with a message that does not mention the key. Check here, where the
        # remedy is obvious.
        if len(session_key) < SECRET_MIN_LENGTH:
            return self.fail(f"Chiave di sessione troppo corta ({len(session_key)}).")
        if len(backup_token) < SECRET_MIN_LENGTH:
            return self.fail(f"Token di backup troppo corto ({len(backup_token)}).")

        engine = config.get("engine", "postgresql")
        port = int(config.get("port", DEFAULT_PORT))
        data_dir = config.get("data_dir")

        lines = [
            "# Employee Scheduling — generated by the installation wizard.",
            "# Contains credentials: do not copy it or commit it to version control.",
            f"QUARKUS_PROFILE={engine}",
            f"QUARKUS_HTTP_PORT={port}",
            # Redundant with -Dapp.data.dir in the unit, but it also lets the
            # uninstaller find the right directory when it is not the default.
            f"APP_DATA_DIR={data_dir}",
            f"AUTH_SESSION_KEY={session_key}",
            f"BACKUP_ADMIN_TOKEN={backup_token}",
        ]

        if engine == "postgresql":
            password = config.get("db_password") or existing.get("DATABASE_PASSWORD", "")
            if not password:
                return self.fail("Password del database mancante.",
                                 "Rilancia il wizard dal passo del database.")
            lines += [
                f"DATABASE_URL={config.get('db_url')}",
                f"DATABASE_USERNAME={DB_USER}",
                f"DATABASE_PASSWORD={password}",
            ]

        # Reuse email configuration just like the session key. Otherwise an
        # update without --smtp-host would write QUARKUS_MAILER_MOCK=true and
        # silently stop delivery: registration codes would only appear in the
        # log again, with no obvious link to an update performed days earlier.
        smtp_host = config.get("smtp_host") or existing.get("QUARKUS_MAILER_HOST", "")
        if smtp_host and not config.get("smtp_host"):
            runner.log("    configurazione email ripresa dall'installazione esistente")
            config.setdefault("smtp_user", existing.get("QUARKUS_MAILER_USERNAME", ""))
            config.setdefault("smtp_pass", existing.get("QUARKUS_MAILER_PASSWORD", ""))
            config.setdefault("smtp_port", existing.get("QUARKUS_MAILER_PORT", 587))
            config.setdefault("smtp_from", existing.get("QUARKUS_MAILER_FROM", ""))
        if smtp_host:
            # Quotes are mandatory: a sender such as "Shifts <shifts@example.com>"
            # contains spaces, and systemd would truncate an unquoted value.
            # Inside quotes, however, systemd interprets C-style escapes: a quote
            # in a password closes the string early. Quarkus would receive a
            # truncated password and delivery would fail with "authentication
            # failed," with nothing linking the failure to that character.
            # Hence the explicit escaping.
            lines += [
                "QUARKUS_MAILER_MOCK=false",
                f'QUARKUS_MAILER_HOST="{_escape(smtp_host)}"',
                f"QUARKUS_MAILER_PORT={config.get('smtp_port', 587)}",
                f'QUARKUS_MAILER_USERNAME="{_escape(config.get("smtp_user", ""))}"',
                f'QUARKUS_MAILER_PASSWORD="{_escape(config.get("smtp_pass", ""))}"',
                f'QUARKUS_MAILER_FROM="{_escape(config.get("smtp_from") or config.get("smtp_user", ""))}"',
                "QUARKUS_MAILER_START_TLS=REQUIRED",
            ]
        else:
            lines.append("QUARKUS_MAILER_MOCK=true")
            if engine == "postgresql":
                runner.log("    [attenzione] Nessun SMTP configurato: il codice di registrazione")
                runner.log("                 comparira' solo nel log del servizio.")

        # 640 root:service — the service can read it; no other user can.
        ok, err = runner.write(ENV_FILE, "\n".join(lines) + "\n", mode=0o640)
        if not ok:
            return self.fail(err)
        if not runner.dry_run:
            runner.run(["chown", f"root:{config.get('service_user', 'employee-scheduling')}",
                        str(ENV_FILE)])

        config["backup_token"] = backup_token
        return self.done(f"Scritta in {ENV_FILE}")
