CREATE TABLE structures (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, address TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT ''
);

CREATE TABLE employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE, first_name TEXT NOT NULL, last_name TEXT NOT NULL,
    structure_id INTEGER NOT NULL DEFAULT 1, active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    email TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE
);

CREATE TABLE specialists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE, first_name TEXT NOT NULL, last_name TEXT NOT NULL,
    structure_id INTEGER NOT NULL DEFAULT 1, active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    email TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE
);

CREATE TABLE locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, l_order INTEGER, code TEXT UNIQUE,
    structure_id INTEGER NOT NULL DEFAULT 1, active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    specialist_id INTEGER,
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE,
    FOREIGN KEY (specialist_id) REFERENCES specialists(id) ON DELETE SET NULL
);

CREATE TABLE skill_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, description TEXT
);

CREATE TABLE skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE, skill_order INTEGER,
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1))
);

CREATE TABLE employee_date_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, description TEXT
);

CREATE TABLE employee_dates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL, date_start TEXT NOT NULL, date_end TEXT NOT NULL, date_type_id INTEGER NOT NULL,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    FOREIGN KEY (date_type_id) REFERENCES employee_date_type(id) ON DELETE CASCADE
);

CREATE TABLE employee_skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL, skill_id INTEGER NOT NULL,
    UNIQUE (employee_id, skill_id),
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE
);

CREATE TABLE location_skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER NOT NULL, skill_id INTEGER NOT NULL, skill_type_id INTEGER NOT NULL,
    UNIQUE (location_id, skill_id, skill_type_id),
    FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_type_id) REFERENCES skill_type(id) ON DELETE CASCADE
);

CREATE TABLE shifts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER NOT NULL, start_time TEXT NOT NULL, end_time TEXT NOT NULL,
    employee_id INTEGER, pinned INTEGER NOT NULL DEFAULT 0 CHECK (pinned IN (0, 1)),
    FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE TABLE shift_skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id INTEGER NOT NULL, skill_id INTEGER NOT NULL, skill_type_id INTEGER NOT NULL,
    UNIQUE (shift_id, skill_id, skill_type_id),
    FOREIGN KEY (shift_id) REFERENCES shifts(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_type_id) REFERENCES skill_type(id) ON DELETE CASCADE
);

CREATE TABLE operator_specialist_affinity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id INTEGER NOT NULL, specialist_id INTEGER NOT NULL, type INTEGER NOT NULL,
    UNIQUE (operator_id, specialist_id),
    FOREIGN KEY (operator_id) REFERENCES employees(id) ON DELETE CASCADE,
    FOREIGN KEY (specialist_id) REFERENCES specialists(id) ON DELETE CASCADE
);

CREATE TABLE shift_template_headers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id INTEGER NOT NULL, description TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE
);

CREATE TABLE shift_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id INTEGER NOT NULL, day_of_week INTEGER NOT NULL,
    start_time TEXT NOT NULL, end_time TEXT NOT NULL, location_id INTEGER NOT NULL, header_id INTEGER,
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE,
    FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
    FOREIGN KEY (header_id) REFERENCES shift_template_headers(id) ON DELETE CASCADE
);

CREATE TABLE shift_template_skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id INTEGER NOT NULL, skill_id INTEGER NOT NULL, skill_type_id INTEGER NOT NULL,
    UNIQUE (template_id, skill_id, skill_type_id),
    FOREIGN KEY (template_id) REFERENCES shift_templates(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_type_id) REFERENCES skill_type(id) ON DELETE CASCADE
);

CREATE TABLE shift_template_meta (
    structure_id INTEGER PRIMARY KEY, description TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE
);

CREATE TABLE languages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE, description TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 0 CHECK (active IN (0, 1))
);

CREATE TABLE labels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE, description TEXT NOT NULL
);

CREATE TABLE localizzazioni (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL, entity_id INTEGER NOT NULL, field_name TEXT NOT NULL,
    language_id INTEGER NOT NULL, value TEXT NOT NULL,
    UNIQUE (entity_type, entity_id, field_name, language_id),
    FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE CASCADE
);

CREATE TABLE general_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id INTEGER NOT NULL UNIQUE, shift_window_mode TEXT NOT NULL DEFAULT 'month',
    auto_populate_from_template INTEGER NOT NULL DEFAULT 0 CHECK (auto_populate_from_template IN (0, 1)),
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE
);

CREATE TABLE email_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id INTEGER NOT NULL UNIQUE, subject TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE
);

CREATE TABLE pdf_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id INTEGER NOT NULL UNIQUE, header_text TEXT NOT NULL DEFAULT '', footer_text TEXT NOT NULL DEFAULT '',
    logo_data_url TEXT NOT NULL DEFAULT '', primary_color TEXT NOT NULL DEFAULT '#2980B9',
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE
);

CREATE TABLE email_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1), host TEXT NOT NULL DEFAULT '', port INTEGER NOT NULL DEFAULT 587,
    start_tls INTEGER NOT NULL DEFAULT 1 CHECK (start_tls IN (0, 1)), username TEXT NOT NULL DEFAULT '',
    password TEXT NOT NULL DEFAULT '', mail_from TEXT NOT NULL DEFAULT ''
);

CREATE TABLE email_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id INTEGER NOT NULL, employee_id INTEGER NOT NULL, period_slug TEXT NOT NULL,
    period_label TEXT NOT NULL DEFAULT '', sent_to TEXT NOT NULL DEFAULT '', filename TEXT NOT NULL DEFAULT '', sent_at TEXT NOT NULL,
    UNIQUE (structure_id, employee_id, period_slug),
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE TABLE solver_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id INTEGER NOT NULL UNIQUE,
    max_solve_seconds INTEGER NOT NULL DEFAULT 30, unimproved_seconds INTEGER NOT NULL DEFAULT 0,
    minimum_rest_hours INTEGER NOT NULL DEFAULT 10, max_shifts_per_day INTEGER NOT NULL DEFAULT 1,
    desired_date_weight INTEGER NOT NULL DEFAULT 1, undesired_date_weight INTEGER NOT NULL DEFAULT 1,
    balance_weight INTEGER NOT NULL DEFAULT 1, optional_skill_weight INTEGER NOT NULL DEFAULT 1,
    balance_by_hours INTEGER NOT NULL DEFAULT 1 CHECK (balance_by_hours IN (0, 1)),
    max_weekly_hours INTEGER NOT NULL DEFAULT 0, min_weekly_shifts INTEGER NOT NULL DEFAULT 0,
    max_weekly_shifts INTEGER NOT NULL DEFAULT 0, max_consecutive_days INTEGER NOT NULL DEFAULT 0,
    min_days_off_per_week INTEGER NOT NULL DEFAULT 0,
    allow_unassigned INTEGER NOT NULL DEFAULT 0 CHECK (allow_unassigned IN (0, 1)),
    unassigned_weight INTEGER NOT NULL DEFAULT 10, same_location_weight INTEGER NOT NULL DEFAULT 0,
    night_balance_weight INTEGER NOT NULL DEFAULT 0, night_start_hour INTEGER NOT NULL DEFAULT 22,
    night_end_hour INTEGER NOT NULL DEFAULT 6,
    stop_when_feasible INTEGER NOT NULL DEFAULT 0 CHECK (stop_when_feasible IN (0, 1)),
    avoid_specialist_weight INTEGER NOT NULL DEFAULT 1, context_days INTEGER NOT NULL DEFAULT 1,
    diminished_window_seconds INTEGER NOT NULL DEFAULT 0, diminished_ratio_pct INTEGER NOT NULL DEFAULT 25,
    weekly_shift_weight INTEGER NOT NULL DEFAULT 1, days_off_weight INTEGER NOT NULL DEFAULT 1,
    consecutive_days_weight INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE
);

CREATE TABLE count_distribution (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count INTEGER NOT NULL, weight DOUBLE PRECISION NOT NULL, type TEXT NOT NULL
);

CREATE TABLE demo_data_parameters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    days_in_schedule INTEGER NOT NULL, employee_count INTEGER NOT NULL, random_seed INTEGER NOT NULL
);

CREATE INDEX idx_employees_structure ON employees(structure_id);
CREATE INDEX idx_specialists_structure ON specialists(structure_id);
CREATE INDEX idx_locations_structure ON locations(structure_id);
CREATE INDEX idx_shifts_location_start_end ON shifts(location_id, start_time, end_time);
CREATE INDEX idx_shift_skills_shift_type_skill ON shift_skills(shift_id, skill_type_id, skill_id);
CREATE INDEX idx_location_skills_location_type_skill ON location_skills(location_id, skill_type_id, skill_id);
CREATE INDEX idx_employee_skills_employee_skill ON employee_skills(employee_id, skill_id);
CREATE INDEX idx_employee_dates_employee_type_start ON employee_dates(employee_id, date_type_id, date_start);
CREATE INDEX idx_osa_operator ON operator_specialist_affinity(operator_id);
CREATE INDEX idx_osa_specialist ON operator_specialist_affinity(specialist_id);
CREATE INDEX idx_shift_templates_header ON shift_templates(header_id);
CREATE INDEX idx_shift_templates_structure ON shift_templates(structure_id);
CREATE INDEX idx_shift_templates_structure_day_start ON shift_templates(structure_id, day_of_week, start_time);
CREATE INDEX idx_shift_template_skills_template_type_skill ON shift_template_skills(template_id, skill_type_id, skill_id);
CREATE INDEX idx_email_log_structure_period ON email_log(structure_id, period_slug);

INSERT INTO structures (id, name, address, phone) OVERRIDING SYSTEM VALUE VALUES (1, 'Default', '', '');
INSERT INTO skill_type (id, description) OVERRIDING SYSTEM VALUE VALUES (1, 'Required'), (2, 'Optional');
INSERT INTO employee_date_type (id, description) OVERRIDING SYSTEM VALUE VALUES
    (1, 'Desired'), (2, 'Undesired'), (3, 'Unavailable');
INSERT INTO languages (id, code, description, active) OVERRIDING SYSTEM VALUE VALUES
    (1, 'it', 'Italiano', 1), (2, 'en', 'English', 0), (3, 'fr', 'Français', 0),
    (4, 'es', 'Español', 0), (5, 'de', 'Deutsch', 0);

ALTER TABLE structures ALTER COLUMN id RESTART WITH 2;
ALTER TABLE skill_type ALTER COLUMN id RESTART WITH 3;
ALTER TABLE employee_date_type ALTER COLUMN id RESTART WITH 4;
ALTER TABLE languages ALTER COLUMN id RESTART WITH 6;
