-- Utenti applicativi che possono autenticarsi.
--
-- Deve restare allineata alla migrazione SQLite corrispondente: stesse colonne, stessi vincoli,
-- stessa semantica. MigrationSchemaParityTest fallisce la build se i due schemi divergono.
--
-- Due soli ruoli: ADMIN (configurazione, backup, utenti) e CAPOSALA (turni, operatori,
-- anagrafiche). La password e' conservata solo come hash bcrypt: 'password_hash' non deve MAI
-- contenere testo in chiaro. Le date usano TEXT come tutto il resto dello schema.
CREATE TABLE app_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    display_name TEXT,
    created_at TEXT NOT NULL,
    last_login_at TEXT
);

CREATE INDEX idx_app_users_username ON app_users(username);
