-- Le competenze diventano proprieta' della singola struttura.
-- Gemella della migrazione SQLite di pari versione: stessa semantica, sintassi nativa.
--
-- Prima: catalogo globale + ponte structure_skills che decideva solo la visibilita'.
-- Rinominare una competenza la cambiava per tutte le strutture, e il vincolo di
-- unicita' sul nome impediva di avere una "Nurse" distinta in due strutture.
--
-- Le assegnazioni esistenti (operatori, sedi, turni, template) vengono azzerate:
-- gli identificativi delle competenze cambiano per costruzione. Rimozione voluta.

-- Stessa forma della gemella SQLite (identita', tipo di active, vincoli in coda):
-- MigrationSchemaParityTest confronta i due contratti dopo aver normalizzato solo le
-- differenze di sintassi note fra i due motori.
CREATE TABLE skills_new (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    skill_order INTEGER,
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    UNIQUE (structure_id, name),
    FOREIGN KEY (structure_id) REFERENCES structures(id) ON DELETE CASCADE
);

-- Una copia del catalogo per ogni struttura: stesso elenco di partenza, righe indipendenti.
INSERT INTO skills_new (structure_id, name, skill_order, active)
SELECT st.id, s.name, s.skill_order, s.active
FROM structures st
CROSS JOIN skills s;

DELETE FROM employee_skills;
DELETE FROM location_skills;
DELETE FROM shift_skills;
DELETE FROM shift_template_skills;

-- Traduzioni indicizzate per identificativo: con gli id cambiati finirebbero sulla
-- competenza sbagliata.
DELETE FROM localizzazioni WHERE entity_type = 'skills';

-- CASCADE e' obbligatorio: PostgreSQL non lascia eliminare una tabella referenziata.
-- Porta pero' via anche le chiavi esterne che puntavano a skills, ricreate sotto dopo
-- la rinomina. Su SQLite il problema non si pone: i vincoli stanno nel corpo delle
-- tabelle e la rinomina li fa tornare validi.
DROP TABLE skills CASCADE;
ALTER TABLE skills_new RENAME TO skills;

ALTER TABLE employee_skills ADD CONSTRAINT employee_skills_skill_id_fkey
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE;
ALTER TABLE location_skills ADD CONSTRAINT location_skills_skill_id_fkey
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE;
ALTER TABLE shift_skills ADD CONSTRAINT shift_skills_skill_id_fkey
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE;
ALTER TABLE shift_template_skills ADD CONSTRAINT shift_template_skills_skill_id_fkey
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE;

-- Il ponte non serve piu': la struttura e' nella riga stessa.
DROP TABLE IF EXISTS structure_skills;

CREATE INDEX IF NOT EXISTS idx_skills_structure ON skills(structure_id, skill_order);
