CREATE TABLE IF NOT EXISTS home_ui_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cover_key TEXT NOT NULL DEFAULT '',
  title_key TEXT NOT NULL DEFAULT 'home.title',
  body_key TEXT NOT NULL DEFAULT 'home.body',
  hint_key TEXT NOT NULL DEFAULT 'home.hint'
);

INSERT INTO home_ui_settings (id, cover_key, title_key, body_key, hint_key)
SELECT 1, '', 'home.title', 'home.body', 'home.hint'
WHERE NOT EXISTS (SELECT 1 FROM home_ui_settings WHERE id = 1);
